### PR TITLE
Update to Blender 2.83.4, Python 3, and Boto 3

### PR DESCRIPTION
**Pull request by msmith93**
Includes:
* Updates the code base to support Python 3 and boto3
* Includes a new public AMI with Blender 2.83.4

### CODE REVIEW

**Comment by gwhobbs** [comment]
@msmith93 Thanks for the PR! I started moving to Python 3 a while back and found it was more work than I expected—and at the time I had some renders I had to get done. 

I noticed a couple of bugs so far with `brenda-run init` (looks like security group setup still uses an older boto API) and `brenda-run spot` (availability zone setting doesn't seem to work with new boto). I'm going to go ahead and merge this PR into a `python-3` branch, apply fixes to those two things, and allow some time for other potential issues come up. 

Looks like you have some interesting plans for future development, which is great! In case you're not familiar with them, there are a few related projects you might find interesting:
* [Flamenco](https://www.flamenco.io) (open-source render manager from the Blender Foundation that also works with [Azure Batch](https://github.com/Azure/flamenco-manager-azure))
* [Crowdrender](https://www.crowd-render.com) (not open-source but could presumably work with EC2 spot instances, with some nice interactivity features)
* [Barista](https://blendermarket.com/products/barista) (from CG Cookie—haven't tried it but it looks sort of like brenda with a GUI)

Also noteworthy are a couple of previous attempts to make brenda more appealing to new users:
* [Renderbot](https://github.com/renderbot/renderbot)
* [brenda-web](https://github.com/robksawyer/brenda-web)

brenda is still my default tool of choice for getting a big animation rendered simply because it works and I know how to use it. I haven't tested Flamenco—I just mention it because it's on my radar of interesting Blender render farm tools. My guess is Flamenco is better-suited to larger production environments with multiple users and many scenes, brenda is probably simpler to setup for small shops needing to quickly and cost-effectively render computationally expensive animations from time to time, and CrowdRender is probably better for when you are in the process of working on a scene and just want to see what the render is going to look like faster. Barista looks a whole lot like brenda, with a GUI, better documentation, and some misc. UX improvements—but it's not open-source.

Anyway, I was thinking through all this a few months ago when I was trying to figure out the future of brenda / how it is positioned within the landscape of (underutilized) cloud rendering solutions. There seems to be a very small number of people currently doing Blender rendering on AWS / Azure / GCP, despite the cost advantages. I'd be interested to get your thoughts on this.

**Comment by msmith93** [comment]
Thanks for the links! I'll check them out. I was struggling to find anything better than Brenda, so I was going to try to work off of a fork of my own. I'll check out those other options instead, thanks for potentially saving me some time ;)

**Comment by msmith93** [comment]
Good catch on the `brenda-run init` failure. I didn't test it out on a fresh account. I also didn't test out all of the different options for commands, so there may be other problems. I mainly wanted to open up this PR to see if this project was still active (I got the info I wanted and more, thanks!)

**Comment by gwhobbs** [comment]
@msmith93 I'd love to see brenda evolve. I do think the apparent success of Barista is at least some validation that something like brenda can hold its own. But it's a fairly niche solution since it really only services single users or maybe small teams yet also requires operational knowledge of AWS. Would be interested to know what you wind up deciding.

**Comment by msmith93** [comment]
Ya, ideally the tool would abstract AWS knowledge away as much as possible. I'm not super experienced with Blender, but it would be cool if the user input would simply be:
* A .blend file
* A desired render time (in minutes)
* A maximum cost?

Then brenda would analyze the .blend file, determine what kind of infra to spin up to perform the render in the desired time at optimal cost, then return the estimated cost to the user before they approve the render to initiate. I don't know if that kind of info can be determined from analyzing the .blend file, I'll take a look at the other projects to see what is out there.

Barista looks cool :)

**Comment by gwhobbs** [comment]
I think you’ll run into problems estimating the render time of a blend file ahead of time—there are so many factors that can affect render time. Obviously on something like an animation, where you have randomized the frame render order (sometimes one part of an animation is significantly more or less computationally complex than other parts), you can make an increasingly reliable estimate after the first few frames. 

That said, there’s plenty of room for UX improvements to brenda—and maybe an automatic mode for new users that makes a lot of decisions for you. It would be interesting to see in more detail how Barista has tackled some of the UX issues as that is something that seems to be aimed at a wider audience.

**Pull request merged**
